
-- 관계 : USER와 BOARD는 1:N 관계, BOARD와 REPLY은 1:N관계
CREATE TABLE IF NOT EXISTS BOARD (
	BNO BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(500) NOT NULL,
	USER_ID VARCHAR(20) NOT NULL,
	CONTENTS TEXT NOT NULL,
	REG_AT DATETIME DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS USR(
	USER_ID VARCHAR(20) NOT NULL PRIMARY KEY,
	PASSWD VARCHAR(200) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS REPLY(
	RNO BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USER_ID VARCHAR(20) NOT NULL,
	BNO BIGINT NOT NULL,
	REPLY_CONTENTS TEXT NOT NULL
);